jwt:
  secret:
    key: s0lZG6PZrKPP+yzYNOD+6oeY+h/tyBbJqFEn/uHga6roxJkOJJmg6yZzk14paa19kGbuRx+NSfbhQH2HxsUxwQ==

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_advanced
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true